/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Utilisateurs.Administrateur;
import Utilisateurs.Professeur;
import Utilisateurs.Utilisateur;
import hibernate.HibernateUtil;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 *
 * @author Raphaël
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
        error_label.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuthentPanel = new javax.swing.JPanel();
        authent_label = new javax.swing.JLabel();
        login_label = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        label_mdp = new javax.swing.JLabel();
        btn_connecter = new javax.swing.JButton();
        login_text = new javax.swing.JTextField();
        error_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        AuthentPanel.setBackground(new java.awt.Color(94, 206, 255));
        AuthentPanel.setName("AuthentPanel"); // NOI18N

        authent_label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        authent_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authent_label.setText("Authentification");
        authent_label.setName("authent_label"); // NOI18N

        login_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_label.setText("Login");
        login_label.setName("login_label"); // NOI18N

        password_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_field.setBorder(null);
        password_field.setName("password_field"); // NOI18N

        label_mdp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_mdp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mdp.setText("Mot de passe");
        label_mdp.setName("label_mdp"); // NOI18N

        btn_connecter.setText("Se connecter");
        btn_connecter.setName("btn_connecter"); // NOI18N
        btn_connecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_connecterMouseClicked(evt);
            }
        });

        login_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_text.setBorder(null);
        login_text.setName("login_text"); // NOI18N

        error_label.setBackground(new java.awt.Color(204, 204, 204));
        error_label.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        error_label.setForeground(new java.awt.Color(255, 0, 0));
        error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_label.setText("Login ou mot de passe incorrect ! Veuillez ressayer.");
        error_label.setName("error_label"); // NOI18N

        javax.swing.GroupLayout AuthentPanelLayout = new javax.swing.GroupLayout(AuthentPanel);
        AuthentPanel.setLayout(AuthentPanelLayout);
        AuthentPanelLayout.setHorizontalGroup(
            AuthentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authent_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_mdp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AuthentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AuthentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AuthentPanelLayout.createSequentialGroup()
                        .addGroup(AuthentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password_field)
                            .addComponent(btn_connecter, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AuthentPanelLayout.createSequentialGroup()
                        .addComponent(login_text, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))))
            .addComponent(error_label, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        AuthentPanelLayout.setVerticalGroup(
            AuthentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthentPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(authent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(login_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_text, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(label_mdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_connecter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        login_text.getAccessibleContext().setAccessibleParent(login_text);
        error_label.getAccessibleContext().setAccessibleName("");
        error_label.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AuthentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AuthentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_connecterMouseClicked
        // TODO add your handling code here:
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session s = sf.openSession();
        Transaction tx = s.beginTransaction();
        boolean admin, prof = false;
        admin = checkIfUserIsAdmin(s);
        prof = checkIfUserIsProf(s);
        if (admin) {
            new IHMforAdmin().setVisible(true);
            this.dispose();
        } else if (prof) {
            new IHMforClient().setVisible(true);
            this.dispose();
        } else {
            error_label.setVisible(true);
        }
        s.flush();
        s.close();
    }//GEN-LAST:event_btn_connecterMouseClicked

    public boolean checkIfUserIsAdmin(Session s) {
        Query q = s.createQuery("Select admin from Administrateur admin");
        boolean flag = false;
        List<Utilisateur> l1 = q.list();
        for (Utilisateur emp : l1) {
            if ((emp.getLogin().equals(login_text.getText())) && (emp.getMdp().equals(password_field.getText()))) {
                flag = true;
            }
        }
        return flag;
    }

    public boolean checkIfUserIsProf(Session s) {
        Query q = s.createQuery("Select prof from Professeur prof");
        boolean flag = false;
        List<Utilisateur> l1 = q.list();
        for (Utilisateur emp : l1) {
            if ((emp.getLogin().equals(login_text.getText())) && (emp.getMdp().equals(password_field.getText()))) {
                flag = true;
            }
        }
        System.out.println(flag);
        return flag;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SessionFactory sf = HibernateUtil.getSessionFactory();
                Session session = sf.openSession();
                new Authentification().setVisible(true);
                Transaction tx = session.beginTransaction();
                Utilisateur emp = new Administrateur();
                emp.setLogin("rhenin");
                emp.setMdp("test");
                emp.setNom("Henin");
                emp.setPrenom("Raphaël");
                session.save(emp);
                Utilisateur prof = new Professeur();
                prof.setLogin("agarcia");
                prof.setMdp("test");
                prof.setNom("Garcia");
                prof.setPrenom("Alexandre");
                session.save(prof);
                session.flush();
                tx.commit();
                session.close();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AuthentPanel;
    private javax.swing.JLabel authent_label;
    private javax.swing.JButton btn_connecter;
    private javax.swing.JLabel error_label;
    private javax.swing.JLabel label_mdp;
    private javax.swing.JLabel login_label;
    private javax.swing.JTextField login_text;
    private javax.swing.JPasswordField password_field;
    // End of variables declaration//GEN-END:variables
}
